export const LIST_ALL_UNIVERSITIES = "LIST_ALL_UNIVERSITIES";
export const LIST_ALL_LEADS = "LIST_ALL_LEADS";
export const LIST_ALL_APPLICATIONS = "LIST_ALL_APPLICATIONS";
export const LIST_PROGRAMMS = "LIST_PROGRAMMS";
export const LIST_ALL_CURRENCIES = "LIST_ALL_CURRENCIES";
export const LIST_ALL_BACKUPS = "LIST_ALL_BACKUPS";
export const LIST_ALL_BRANCHES = "LIST_ALL_BRANCHES";
export const LIST_ALL_USERS="LIST_ALL_USERS"
export const LIST_ALL_ACTIVITIES="LIST_ALL_ACTIVITIES"
export const LIST_ALL_PROERTIES="LIST_ALL_PROERTIES"


//
export const VIEW_UNIVERSITY_DETAILS = "VIEW_UNIVERSITY_DETAILS";
export const VIEW_LEAD_DETAILS = "VIEW_LEAD_DETAILS";
export const APPLICATION_DETAILS = "APPLICATION_DETAILS";
export const VIEW_PROGRAMME_DETAILS = "VIEW_PROGRAMME_DETAILS";
export const VIEW_CURRENCY_DETAILS = "VIEW_CURRENCY_DETAILS";
export const VIEW_ALL_BRANCH = "VIEW_ALL_BRANCH";
export const VIEW_ALL_USERS = "VIEW_ALL_USERS";
export const DELETE_BACKUP_FILE = "DELETE_BACKUP_FILE";
export const DOWNLOAD_BACKUP_FILE = "DOWNLOAD_BACKUP_FILE";
export const RESTORE_BACKUP_FILE = "RESTORE_BACKUP_FILE";



// http://localhost:8080/v1/front/activities/list